#!/bin/sh
code --install-extension aaron-bond.better-comments \
     --install-extension alefragnani.Bookmarks \
     --install-extension baincd.copy-path-unixstyle \
     --install-extension cheshirekow.cmake-format \
     --install-extension cschlosser.doxdocgen \
     --install-extension DavidAnson.vscode-markdownlint \
     --install-extension deckerio.breakpointio \
     --install-extension donjayamanne.githistory \
     --install-extension DotJoshJohnson.xml \
     --install-extension dtsvet.vscode-wasm \
     --install-extension fernandoescolar.vscode-solution-explorer \
     --install-extension foxundermoon.shell-format \
     --install-extension fredericbonnet.cmake-test-adapter \
     --install-extension GitLab.gitlab-workflow \
     --install-extension hbenl.vscode-test-explorer \
     --install-extension jeff-hykin.better-cpp-syntax \
     --install-extension josetr.cmake-language-support-vscode \
     --install-extension maattdd.gitless \
     --install-extension matepek.testmate-cpp-legacy \
     --install-extension mhutchie.git-graph \
     --install-extension ms-azuretools.vscode-docker \
     --install-extension ms-dotnettools.vscode-dotnet-runtime \
     --install-extension ms-vscode-remote.remote-containers \
     --install-extension ms-vscode-remote.remote-ssh \
     --install-extension ms-vscode-remote.remote-ssh-edit \
     --install-extension ms-vscode-remote.remote-wsl \
     --install-extension ms-vscode-remote.vscode-remote-extensionpack \
     --install-extension ms-vscode.cmake-tools \
     --install-extension ms-vscode.cpptools \
     --install-extension ms-vscode.cpptools-extension-pack \
     --install-extension ms-vscode.cpptools-themes \
     --install-extension ms-vscode.powershell \
     --install-extension ms-vscode.test-adapter-converter \
     --install-extension mtib.vsgx \
     --install-extension natessilva.ts-prop-dag \
     --install-extension oderwat.indent-rainbow \
     --install-extension Remisa.shellman \
     --install-extension rogalmic.bash-debug \
     --install-extension shaharkazaz.git-merger \
     --install-extension technosophos.vscode-make \
     --install-extension timonwong.shellcheck \
     --install-extension twxs.cmake \
     --install-extension usernamehw.errorlens \
     --install-extension xaver.clang-format \
     --install-extension yzhang.markdown-all-in-one
 