#!/bin/sh
code --install-extension aaron-bond.better-comments
code --install-extension alefragnani.Bookmarks
code --install-extension baincd.copy-path-unixstyle
code --install-extension cheshirekow.cmake-format
code --install-extension cschlosser.doxdocgen
code --install-extension deckerio.breakpointio
code --install-extension donjayamanne.githistory
code --install-extension DotJoshJohnson.xml
code --install-extension dtsvet.vscode-wasm
code --install-extension fernandoescolar.vscode-solution-explorer
code --install-extension foxundermoon.shell-format
code --install-extension fredericbonnet.cmake-test-adapter
code --install-extension gitkraken.gitkraken-authentication
code --install-extension GitLab.gitlab-workflow
code --install-extension hbenl.vscode-test-explorer
code --install-extension jeff-hykin.better-cpp-syntax
code --install-extension maattdd.gitless
code --install-extension matepek.vscode-catch2-test-adapter
code --install-extension mhutchie.git-graph
code --install-extension ms-vscode-remote.remote-containers
code --install-extension ms-vscode-remote.remote-ssh
code --install-extension ms-vscode-remote.remote-ssh-edit
code --install-extension ms-vscode-remote.remote-wsl
code --install-extension ms-vscode-remote.vscode-remote-extensionpack
code --install-extension ms-vscode.cmake-tools
code --install-extension ms-vscode.cpptools
code --install-extension ms-vscode.cpptools-extension-pack
code --install-extension ms-vscode.cpptools-themes
code --install-extension ms-vscode.powershell
code --install-extension ms-vscode.test-adapter-converter
code --install-extension mtib.vsgx
code --install-extension oderwat.indent-rainbow
code --install-extension Remisa.shellman
code --install-extension shaharkazaz.git-merger
code --install-extension technosophos.vscode-make
code --install-extension timonwong.shellcheck
code --install-extension twxs.cmake
code --install-extension usernamehw.errorlens
code --install-extension xaver.clang-format
code --install-extension yzhang.markdown-all-in-one
code --install-extension znck.grammarly
